name: Build, Push & Deploy to Scaleway

on:
  push:
    branches: [main]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    env:
      SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
      SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
      SCW_PROJECT_ID: ${{ secrets.SCW_PROJECT_ID }}
      SCW_DEFAULT_REGION: fr-par
      NAMESPACE: namespace-breton-swan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          registry: rg.fr-par.scw.cloud
          username: ${{ env.SCW_ACCESS_KEY }}
          password: ${{ env.SCW_SECRET_KEY }}

      - name: Build and push back image
        uses: docker/build-push-action@v5
        with:
          context: ./back
          push: true
          tags: rg.fr-par.scw.cloud/${{ env.NAMESPACE }}/back:latest

      - name: Build and push front image
        uses: docker/build-push-action@v5
        with:
          context: ./front
          push: true
          tags: rg.fr-par.scw.cloud/${{ env.NAMESPACE }}/front:latest

      - name: Install Scaleway CLI
        run: |
          curl -sSL https://install.scaleway.com | bash
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Configure Scaleway CLI
        run: |
          scw config set project-id $SCW_PROJECT_ID
          scw config set access-key $SCW_ACCESS_KEY
          scw config set secret-key $SCW_SECRET_KEY
          scw config set default-region $SCW_DEFAULT_REGION

      - name: Deploy back container
        run: |
          scw container container create name=back image=rg.${SCW_DEFAULT_REGION}.scw.cloud/${NAMESPACE}/back:latest port=3000 || echo "Back container already exists"
          scw container container list name=back -o json | jq -r '.[0].id' | xargs -I {} scw container container deploy {}

      - name: Deploy front container
        run: |
          scw container container create name=front image=rg.${SCW_DEFAULT_REGION}.scw.cloud/${NAMESPACE}/front:latest port=80 env="VITE_API_URL=https://back.${SCW_DEFAULT_REGION}.scalewayapp.com" || echo "Front container already exists"
          scw container container list name=front -o json | jq -r '.[0].id' | xargs -I {} scw container container deploy {}
