name: Build, Push and Deploy to Scaleway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          registry: rg.fr-par.scw.cloud
          username: ${{ secrets.SCW_ACCESS_KEY }}
          password: ${{ secrets.SCW_SECRET_KEY }}

      - name: Build and push back image
        uses: docker/build-push-action@v5
        with:
          context: ./back
          push: true
          tags: rg.fr-par.scw.cloud/breton-swan/back:latest

      - name: Build and push front image
        uses: docker/build-push-action@v5
        with:
          context: ./front
          push: true
          tags: rg.fr-par.scw.cloud/breton-swan/front:latest

      - name: Install Scaleway CLI
        run: |
          curl -sSL https://install.scaleway.com | bash
          echo "$HOME/bin" >> $GITHUB_PATH
          echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Deploy containers to Scaleway
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          SCW_DEFAULT_REGION: fr-par
        run: |
          scw init secret-key=$SCW_SECRET_KEY access-key=$SCW_ACCESS_KEY project-id=$SCW_DEFAULT_PROJECT_ID region=$SCW_DEFAULT_REGION zone=fr-par-1 install-cli=false
          
          scw container container create name=back \
            image=rg.fr-par.scw.cloud/breton-swan/back:latest \
            port-mapping='80:3000' \
            privacy=public || echo "Back container already exists"

          scw container container deploy name=back

          scw container container create name=front \
            image=rg.fr-par.scw.cloud/breton-swan/front:latest \
            port-mapping='80:80' \
            privacy=public || echo "Front container already exists"

          scw container container deploy name=front
