name: Publish Docker image to Scaleway

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Scaleway Container Registry
      env:
        SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
      run: echo "${SCW_SECRET_KEY}" | docker login rg.fr-par.scw.cloud -u _token --password-stdin

    - name: Build and Push Front image
      run: |
        docker build -t rg.fr-par.scw.cloud/namespace-breton-swan/front:latest ./devops-dev/front
        docker push rg.fr-par.scw.cloud/namespace-breton-swan/front:latest

    - name: Build and Push Back image
      run: |
        docker build -t rg.fr-par.scw.cloud/namespace-breton-swan/back:latest ./devops-dev/back
        docker push rg.fr-par.scw.cloud/namespace-breton-swan/back:latest
