name: Build, Push & Deploy to Scaleway

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    env:
      SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
      SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
      SCW_PROJECT_ID: ${{ secrets.SCW_PROJECT_ID }}
      SCW_DEFAULT_REGION: fr-par
      NAMESPACE: breton-swan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          registry: rg.${{ env.SCW_DEFAULT_REGION }}.scw.cloud
          username: ${{ env.SCW_ACCESS_KEY }}
          password: ${{ env.SCW_SECRET_KEY }}

      - name: Build and push back image
        uses: docker/build-push-action@v5
        with:
          context: ./back
          push: true
          tags: rg.${{ env.SCW_DEFAULT_REGION }}.scw.cloud/${{ env.NAMESPACE }}/back:latest

      - name: Build and push front image
        uses: docker/build-push-action@v5
        with:
          context: ./front
          push: true
          tags: rg.${{ env.SCW_DEFAULT_REGION }}.scw.cloud/${{ env.NAMESPACE }}/front:latest

      - name: Install Scaleway CLI
        run: |
          sudo apt update
          sudo apt install -y curl gnupg2 software-properties-common
          curl -fsSL https://packages.scaleway.com/scaleway.key | sudo tee /etc/apt/trusted.gpg.d/scaleway.asc
          echo "deb https://packages.scaleway.com/debian stable main" | sudo tee /etc/apt/sources.list.d/scaleway.list
          sudo apt update
          sudo apt install -y scaleway-cli

      - name: Configure Scaleway CLI
        run: |
          scw config set project-id ${{ env.SCW_PROJECT_ID }}
          scw config set access-key ${{ env.SCW_ACCESS_KEY }}
          scw config set secret-key ${{ env.SCW_SECRET_KEY }}
          scw config set default-region ${{ env.SCW_DEFAULT_REGION }}

      - name: Create & Deploy back container
        run: |
          scw container container create name=back image=rg.${{ env.SCW_DEFAULT_REGION }}.scw.cloud/${{ env.NAMESPACE }}/back:latest port=3000 || echo "Back container already exists"
          scw container container list name=back -o json | jq -r '.[0].id' | xargs -I {} scw container container deploy {}

      - name: Create & Deploy front container
        run: |
          scw container container create name=front image=rg.${{ env.SCW_DEFAULT_REGION }}.scw.cloud/${{ env.NAMESPACE }}/front:latest port=80 env="VITE_API_URL=https://back.${{ env.SCW_DEFAULT_REGION }}.scalewayapp.com" || echo "Front container already exists"
          scw container container list name=front -o json | jq -r '.[0].id' | xargs -I {} scw container container deploy {}
