name: Build, Push and Deploy to Scaleway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          registry: rg.fr-par.scw.cloud
          username: ${{ secrets.SCW_ACCESS_KEY }}
          password: ${{ secrets.SCW_SECRET_KEY }}

      - name: Build and push back image
        uses: docker/build-push-action@v5
        with:
          context: ./back
          push: true
          tags: rg.fr-par.scw.cloud/breton-swan/back:latest

      - name: Build and push front image
        uses: docker/build-push-action@v5
        with:
          context: ./front
          push: true
          tags: rg.fr-par.scw.cloud/breton-swan/front:latest

      - name: Install Scaleway CLI
        run: |
          curl -sL https://github.com/scaleway/scaleway-cli/releases/latest/download/scw-linux-amd64 > scw
          chmod +x scw
          sudo mv scw /usr/local/bin/scw

      - name: Configure Scaleway CLI
        run: |
          scw config set access-key=${{ secrets.SCW_ACCESS_KEY }}
          scw config set secret-key=${{ secrets.SCW_SECRET_KEY }}
          scw config set project-id=${{ secrets.SCW_PROJECT_ID }}
          scw config set region=fr-par

      - name: Deploy back container
        run: |
          scw container container deploy back --name back \
            --namespace-id=${{ secrets.SCW_NAMESPACE_ID }} \
            --image=rg.fr-par.scw.cloud/breton-swan/back:latest \
            --port=3000

      - name: Deploy front container
        run: |
          scw container container deploy front --name front \
            --namespace-id=${{ secrets.SCW_NAMESPACE_ID }} \
            --image=rg.fr-par.scw.cloud/breton-swan/front:latest \
            --port=80 \
            --env="BACK_URL=https://<ton-back-end-url>"
